Add flock support.  Might work in Linux now.

diff --git a/run-one b/run-one
--- a/run-one
+++ b/run-one
@@ -48,6 +48,17 @@ if [ $# -eq 0 ]; then
 	exit 64 # EX_USAGE
 fi
 
+locked_command() {
+	if which lockf >/dev/null 2>&1; then
+		exec lockf -st0 "$@"
+	elif which flock >/dev/null 2>&1; then
+		exec flock -xn "$@"
+	else
+		echo "ERROR: Unable to find lockf(1) or flock(1) in PATH" 1>&2
+		exit 69 # EX_UNAVAILABLE
+	fi
+}
+
 : "${RUN_ONCE_LOCKDIR:=}"
 
 if [ -z "${RUN_ONCE_LOCKDIR}" ]; then
@@ -84,7 +95,7 @@ LOCKFILE="${LOCKDIR}/${HASH}"
 NAME="$(basename "$0")"
 case "$NAME" in
 	run-one)
-		exec lockf -st0 "$LOCKFILE" "$@"
+		locked_command "$LOCKFILE" "$@"
 	;;
 	run-this-one)
 		PIDS=$(pkill -u "$USER" -lxf "$*" 2>/dev/null | awk 'BEGIN { ORS=" " } { print $3 }')
@@ -93,11 +104,11 @@ case "$NAME" in
 			pwait -v $PIDS 2>/dev/null
 		fi
 
-		exec lockf -st0 "$LOCKFILE" "$@"
+		locked_command "$LOCKFILE" "$@"
 	;;
 	run-one-constantly|run-one-until-success|run-one-until-failure)
 		# shellcheck disable=SC2016
-		exec lockf -st0 "$LOCKFILE" /bin/sh -c 'backoff=1
+		locked_command "$LOCKFILE" /bin/sh -c 'backoff=1
 		while true; do
 			if "$@"; then
 				[ "$0" = "run-one-until-success" ] && exit "$?"
